services:
  app:
    build:
      context: .
      dockerfile: rate-limiting/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/rate_limiting
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rate_limiting
      - POSTGRES_FORCE_INIT=true
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./rate-limiting/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d rate_limiting" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

volumes:
  pgdata: